### ISSUE TITLE
Mods manually installed via .zip in previous version unable to be removed from Mod Loader

### ISSUE THREAD

**Issue by DustyMustard** [DazoTrove/TroveTools.NET#17]
Long title. Not quite sure how to replicate but also unsure how to fix manually, as I have tried deleting everything I can find associated to the Mod Loader and still these entries show in My Mods.

![1](https://cloud.githubusercontent.com/assets/710289/16497749/6a10b7b8-3ead-11e6-9189-89589ab70d25.png)

From working on the Pip_Boy and Tibee Mod zip files as I was generating them, I must have deleted the original mod zip files after I was done via Windows Explorer rather then through TroveTools.NET. This would of occurred in an earlier version of your Mod Loader.

I am able to delete Pip-Boy from the list with selecting it and hitting Remove Mod, but when I restart TroveTools.Net it is back again.
I cannot select Tibee-Dusy_Mustard_Llama(2) at all, so I am unable to select it and hit Remove mod.

I have tried removing the TroveTools.Net folder out of %appdata%, removing the click once data application like was advised in the previous bug report, uninstalling TroveTools.Net through Programs & Features.

I am unable to find a way to remove these two entries. Installing Pip-Boy again creates a new entry of it, so not a fix.

I imagine I could try creating a false entry of those mods and reloading the application. Would be nice if there was an override to remove entries somehow, a force delete of sorts.

**Comment by DustyMustard** [comment]
Not sure making a fake file will trick it, as Pip-Boy it recognizes off the Mod Directory and will download and install it into the entry already listed, but when I uninstall it then remove it, opening the application again shows the Pip-Bo listing again.

**Comment by DazoTrove** [comment]
I tried to reproduce the issue on my system, but the issue of removed mods showing back up when launching the program has not happened for me yet.

The user application settings data including the list of **My Mods** is stored in folders under `%LocalAppData%\Dazo` in `user.config` files. You can try deleting these folders to reset to the default settings.

I'm not sure whether this is related to your issue, but this info may help. When there are no mods in the My Mods list the program attempts to look in the following two folders to automatically add them:
- `%AppData%\TroveTools.NET\mods`
- `%AppData%\Trove Toolbox\mods`

You can delete or move unneeded mod zip files out of those two folders to prevent them from re-appearing.

**Comment by DazoTrove** [comment]
In testing this I found a couple of bugs (some style or design related) and one application crash due to an error. The next release will include these updates:
- Mod Detail Pane: fixed date/time conversion issue for manually loaded mods
- Mod Detail Pane: downloads table is hidden for manually loaded mods that have no downloads
- My Mods: fixed update button to only display when a valid Trovesaurus ID and downloads are found for the mod

**Comment by DustyMustard** [comment]
Though I am sure I cleared all those locations before, did it again and listings are finally gone.

Thank you.
