### ISSUE TITLE
Allow the ability to set an Installed mod to Skip Updates.

### ISSUE THREAD

**Issue by willgk** [DazoTrove/TroveTools.NET#19]
There are numerous mods that do differing versions inside the same mod that have different features per version, for instance the Spicy Shadow Drops mod. v1 is the one everyone wants (mostly everyone) due to the column of light, whereas the latest version is the minimalist version. So when we hit Update All it overwrites the mod with that later version. Please add a feature that will let us Skip Updates or Disable Updating, whatever you want to call it on a per mod basis. So we can skip over that mod when performing an Update All.

**Comment by willgk** [comment]
Sorry, I dont see a way to set this as an Enhancement request, or I would. Love your program bud! A+++ on it :+1:

**Comment by DazoTrove** [comment]
Thanks for the feedback. It should not be too difficult to implement an option to disable updates 
on individual mods from the automatic updates and the update all button. If you have this updates disabled on a mod you will still be able to install a different version from the list of mod versions in the mod detail pane.

**Comment by DazoTrove** [comment]
I have implemented this feature and it will be released with the next version: 1.0.0.7
