### ISSUE TITLE
trovetools.net wont work 

### ISSUE THREAD

**Issue by xXBLA2EKILLAXx** [DazoTrove/TroveTools.NET#27]
when ever I download the program it says
Cannot start the application. contact the application vendor for assistance.

PLATFORM VERSION INFO
    Windows             : 10.0.10586.0 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1078.0 built by: NETFXREL3STAGE
    clr.dll             : 4.6.1080.0 built by: NETFXREL3STAGE
    dfdll.dll           : 4.6.1038.0 built by: NETFXREL2
    dfshim.dll          : 10.0.10586.0 (th2_release.151029-1700)

SOURCES
    Deployment url          : https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application
    Deployment Provider url     : https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application
    Application url         : https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/Application%20Files/TroveTools.NET_1_1_4_0/TroveTools.NET.exe.manifest

IDENTITIES
    Deployment Identity     : TroveTools.NET.application, Version=1.1.4.0, Culture=neutral, PublicKeyToken=0570929531b11331, processorArchitecture=msil
    Application Identity        : TroveTools.NET.exe, Version=1.1.4.0, Culture=neutral, PublicKeyToken=0570929531b11331, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
    \* Installable application.
    \* Trust url parameter is set.
ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    \* Activation of https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application resulted in exception. Following failure messages were detected:
        + Exception occurred during store operation.
        + Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
    \* Transaction at [2016-07-18 6:15:19 PM]
        - Staging of a component file (TroveTools.NET.exe) did not succeed.
        - Staging of a component (System.Windows.Interactivity.resources.dll.genman) did not succeed.
        - Staging of a component file (System.Windows.Interactivity.resources.dll) did not succeed.
        - Installation of deployment (https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application#TroveTools.NET.application, Version=1.1.4.0, Culture=neutral, PublicKeyToken=0570929531b11331, processorArchitecture=msil) did not succeed.
        - Setting one or more of the deployment metadata did not succeed.

WARNINGS
    There were no warnings during this operation.

OPERATION PROGRESS STATUS
    \* [2016-07-18 6:15:11 PM] : Activation of https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application has started.
    \* [2016-07-18 6:15:11 PM] : Processing of deployment manifest has successfully completed.
    \* [2016-07-18 6:15:11 PM] : Installation of the application has started.
    \* [2016-07-18 6:15:12 PM] : Processing of application manifest has successfully completed.
    \* [2016-07-18 6:15:13 PM] : Found compatible runtime version 4.0.30319.
    \* [2016-07-18 6:15:13 PM] : Request of trust and detection of platform is complete.
    \* [2016-07-18 6:15:19 PM] : Downloading of subscription dependencies is complete.
    \* [2016-07-18 6:15:19 PM] : Commit of the downloaded application has started.

ERROR DETAILS
    Following errors were detected during this operation.
    \* [2016-07-18 6:15:19 PM] System.Deployment.Application.DeploymentException (ComponentStore)
        - Exception occurred during store operation.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
            at System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
            at System.Deployment.Application.ComponentStore.CommitApplication(SubscriptionState subState, CommitApplicationParams commitParams)
            at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
            at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
        --- Inner Exception ---
        System.UnauthorizedAccessException
        - Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
            at System.Deployment.Internal.Isolation.Store.Transact(StoreTransactionOperation[] operations, UInt32[] rgDispositions, Int32[] rgResults)
            at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)

COMPONENT STORE TRANSACTION DETAILS
    \* Transaction at [2016-07-18 6:15:19 PM]
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: 8EEYKZOX.15N.application
        + System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
            - Status: Set
            - HRESULT: 0x0
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: TroveTools.NET.exe.manifest
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: Resources\TroveTools.ico
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: TroveTools.NET.exe.config
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: HtmlRenderer.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: HtmlRenderer.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: log4net.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: log4net.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: CommonMark.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: CommonMark.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: Humanizer.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: Humanizer.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: Newtonsoft.Json.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: Newtonsoft.Json.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: HtmlRenderer.WPF.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: HtmlRenderer.WPF.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Installed
            - HRESULT: 0x0
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Installed
            - HRESULT: 0x0
            - Manifest: TroveTools.NET.exe.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Failed
            - HRESULT: 0x80070005
            - File: TroveTools.NET.exe
        + System.Deployment.Internal.Isolation.StoreOperationStageComponent
            - Status: Failed
            - HRESULT: 0x1
            - Manifest: System.Windows.Interactivity.resources.dll.genman
        + System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
            - Status: Failed
            - HRESULT: 0x1
            - File: System.Windows.Interactivity.resources.dll
        + System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
            - Status: Failed
            - HRESULT: 0x1
            - AppId: https://raw.githubusercontent.com/DazoTrove/TroveTools.NET/master/TroveTools.NET/publish/TroveTools.NET.application#TroveTools.NET.application, Version=1.1.4.0, Culture=neutral, PublicKeyToken=0570929531b11331, processorArchitecture=msil
        + System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
            - Status: Failed
            - HRESULT: 0x1
        + System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
            - HRESULT: 0x1

**Comment by DazoTrove** [comment]
Try the following and then try launching the application setup program again:
- Clear your user application settings (resets all to default and removes installed mods from the app). Delete the subfolders in the `%LocalAppData%\Dazo\` folder.
- Delete the ClickOnce application cache subfolders in the `%LocalAppData%\Apps\2.0` folder. The app will be re-downloaded when you launch it and may have an install prompt.
- Verify that any virus scanning application hasn't blocked access to the program executable. You may need to add an exception for this program if your virus scanner quarantines or blocks access to the program.

**Comment by xXBLA2EKILLAXx** [comment]
ok I deleted the click-once application I couldn't find the dazo folder to clear the application settings and now when I try to run it it pops up and then closes and I cant use it and made sure that the antiviruse is not stopping it

**Comment by CheatCoder** [comment]
i can open the Trovetools.net, after the latest update, only with administrator privileges.
idk why but i hope this helps a little bit

**Comment by xXBLA2EKILLAXx** [comment]
when I run with administrator privileges it doesn't bring anything up

**Comment by CheatCoder** [comment]
sorry then i have no idea.
I see there " Access is denied" errors and errors that i can't specified.

i can only say to try to uninstall it and then install it again but i think this is not helping ...
